# Use postgres/example user/password credentials
version: '3.9'

services:
  app:
    image: 'agro-admin-fe:1.0.0'
    ports:
      - "4200:80"
    build:
      context: .
    container_name: agro-admin-fe
